# 1 "data/maps/CURSEZONE/scripts.pory"
CURSEZONE_MapScripts::
# 2 "data/maps/CURSEZONE/scripts.pory"
	.byte 0

CURSEZONE_EventScript_YanFight::
# 6 "data/maps/CURSEZONE/scripts.pory"
	lockall
# 7 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_0
# 8 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_1
# 9 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_2
# 10 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_3
# 11 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_4
# 12 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_5
# 13 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_6
# 14 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_7
# 15 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_8
# 16 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_9
# 17 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_10
# 18 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_11
# 19 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_12
# 20 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_13
# 21 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_14
# 22 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_15
# 23 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_16
# 24 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_17
# 25 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_18
# 26 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_19
# 27 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_20
# 28 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_21
# 29 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_22
# 30 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_23
# 31 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_24
# 32 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_25
# 33 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_26
# 34 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_27, MSGBOX_YESNO
# 35 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_28
# 36 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_29
# 37 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_30
# 38 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_31
# 39 "data/maps/CURSEZONE/scripts.pory"
	delay 100
# 40 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_25
# 41 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_32
# 42 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_25
# 43 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_33
# 44 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_34
# 45 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_35
# 46 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_36
# 47 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_25
# 48 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_37
# 49 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_38
# 50 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_39
# 51 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_40
# 52 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_41
# 53 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_42
# 54 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_43
# 55 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_9
# 56 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_44
# 57 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_45
# 58 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_46
# 59 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_47
# 60 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_48
# 61 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_49
# 62 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_50
# 63 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_51
# 64 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_52
# 65 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_53
# 66 "data/maps/CURSEZONE/scripts.pory"
	delay 50
# 67 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_54
# 68 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_55
# 69 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_56
# 70 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_57
# 71 "data/maps/CURSEZONE/scripts.pory"
	msgbox CURSEZONE_EventScript_YanFight_Text_58
# 73 "data/maps/CURSEZONE/scripts.pory"
	releaseall
# 74 "data/maps/CURSEZONE/scripts.pory"
	trainerbattle_single TRAINER_ALEXA, YanIntro, YanOutro
	return


CURSEZONE_EventScript_YanFight_Text_0:
# 7 "data/maps/CURSEZONE/scripts.pory"
	.string ".......$"

CURSEZONE_EventScript_YanFight_Text_1:
# 8 "data/maps/CURSEZONE/scripts.pory"
	.string "It's you...$"

CURSEZONE_EventScript_YanFight_Text_2:
# 9 "data/maps/CURSEZONE/scripts.pory"
	.string "I knew you would run into me\neventually.$"

CURSEZONE_EventScript_YanFight_Text_3:
# 10 "data/maps/CURSEZONE/scripts.pory"
	.string "...take a look around us.$"

CURSEZONE_EventScript_YanFight_Text_4:
# 11 "data/maps/CURSEZONE/scripts.pory"
	.string "There's nothing left, except\nfor me and you.$"

CURSEZONE_EventScript_YanFight_Text_5:
# 12 "data/maps/CURSEZONE/scripts.pory"
	.string "I know...I can't do anything\nto stop you.$"

CURSEZONE_EventScript_YanFight_Text_6:
# 13 "data/maps/CURSEZONE/scripts.pory"
	.string "And even if I could do anything,\nwhat good what it be, right?$"

CURSEZONE_EventScript_YanFight_Text_7:
# 14 "data/maps/CURSEZONE/scripts.pory"
	.string "Who would I even be saving...at that\npoint?.$"

CURSEZONE_EventScript_YanFight_Text_8:
# 15 "data/maps/CURSEZONE/scripts.pory"
	.string "So, that's why I'm not here to stop you.$"

CURSEZONE_EventScript_YanFight_Text_9:
# 16 "data/maps/CURSEZONE/scripts.pory"
	.string "But...$"

CURSEZONE_EventScript_YanFight_Text_10:
# 17 "data/maps/CURSEZONE/scripts.pory"
	.string "I know what you really want.$"

CURSEZONE_EventScript_YanFight_Text_11:
# 18 "data/maps/CURSEZONE/scripts.pory"
	.string "Because truth is...we both want the\nsame thing.$"

CURSEZONE_EventScript_YanFight_Text_12:
# 19 "data/maps/CURSEZONE/scripts.pory"
	.string "I know you. And I know you\nnever liked doing things the easy way.$"

CURSEZONE_EventScript_YanFight_Text_13:
# 20 "data/maps/CURSEZONE/scripts.pory"
	.string "So, how about this.$"

CURSEZONE_EventScript_YanFight_Text_14:
# 21 "data/maps/CURSEZONE/scripts.pory"
	.string "One last game.$"

CURSEZONE_EventScript_YanFight_Text_15:
# 22 "data/maps/CURSEZONE/scripts.pory"
	.string "If you win...do what you want.$"

CURSEZONE_EventScript_YanFight_Text_16:
# 23 "data/maps/CURSEZONE/scripts.pory"
	.string "After all, I'm not opposed to it.$"

CURSEZONE_EventScript_YanFight_Text_17:
# 24 "data/maps/CURSEZONE/scripts.pory"
	.string "But if I win, we do things my\nway.$"

CURSEZONE_EventScript_YanFight_Text_18:
# 25 "data/maps/CURSEZONE/scripts.pory"
	.string "I won't 'join' with you.$"

CURSEZONE_EventScript_YanFight_Text_19:
# 26 "data/maps/CURSEZONE/scripts.pory"
	.string "Instead...$"

CURSEZONE_EventScript_YanFight_Text_20:
# 27 "data/maps/CURSEZONE/scripts.pory"
	.string "The both of us will stay here.$"

CURSEZONE_EventScript_YanFight_Text_21:
# 28 "data/maps/CURSEZONE/scripts.pory"
	.string "We'll stay here until the sun explodes\nand erases us.$"

CURSEZONE_EventScript_YanFight_Text_22:
# 29 "data/maps/CURSEZONE/scripts.pory"
	.string "Do you even remember...how long\nit's been?$"

CURSEZONE_EventScript_YanFight_Text_23:
# 30 "data/maps/CURSEZONE/scripts.pory"
	.string "What's another eternity to us?$"

CURSEZONE_EventScript_YanFight_Text_24:
# 31 "data/maps/CURSEZONE/scripts.pory"
	.string "Just me and you...it's what you've\nwanted anyway.$"

CURSEZONE_EventScript_YanFight_Text_25:
# 32 "data/maps/CURSEZONE/scripts.pory"
	.string "...$"

CURSEZONE_EventScript_YanFight_Text_26:
# 33 "data/maps/CURSEZONE/scripts.pory"
	.string "So...then. What will it be?$"

CURSEZONE_EventScript_YanFight_Text_27:
# 34 "data/maps/CURSEZONE/scripts.pory"
	.string "Shall we do things...my way?$"

CURSEZONE_EventScript_YanFight_Text_28:
# 35 "data/maps/CURSEZONE/scripts.pory"
	.string "........$"

CURSEZONE_EventScript_YanFight_Text_29:
# 36 "data/maps/CURSEZONE/scripts.pory"
	.string "Oh....{PLAYER}...$"

CURSEZONE_EventScript_YanFight_Text_30:
# 37 "data/maps/CURSEZONE/scripts.pory"
	.string "Sorry, I don't mean to be rude, but...$"

CURSEZONE_EventScript_YanFight_Text_31:
# 38 "data/maps/CURSEZONE/scripts.pory"
	.string "I wasn't talking to you.$"

CURSEZONE_EventScript_YanFight_Text_32:
# 41 "data/maps/CURSEZONE/scripts.pory"
	.string "I'm talking to...the person standing\nbehind you.$"

CURSEZONE_EventScript_YanFight_Text_33:
# 43 "data/maps/CURSEZONE/scripts.pory"
	.string "She won't say anything.$"

CURSEZONE_EventScript_YanFight_Text_34:
# 44 "data/maps/CURSEZONE/scripts.pory"
	.string "...ha. I already know her answer.$"

CURSEZONE_EventScript_YanFight_Text_35:
# 45 "data/maps/CURSEZONE/scripts.pory"
	.string "Since you insist on being so shy\ntoday...$"

CURSEZONE_EventScript_YanFight_Text_36:
# 46 "data/maps/CURSEZONE/scripts.pory"
	.string "{PLAYER}, you'll have to do.$"

CURSEZONE_EventScript_YanFight_Text_37:
# 48 "data/maps/CURSEZONE/scripts.pory"
	.string "But before we begin, I need to know.$"

CURSEZONE_EventScript_YanFight_Text_38:
# 49 "data/maps/CURSEZONE/scripts.pory"
	.string "{PLAYER}...$"

CURSEZONE_EventScript_YanFight_Text_39:
# 50 "data/maps/CURSEZONE/scripts.pory"
	.string "Can you tell me...what you've\nbeen trying to accomplish?$"

CURSEZONE_EventScript_YanFight_Text_40:
# 51 "data/maps/CURSEZONE/scripts.pory"
	.string "Maybe you had some guidance at the beginning, but...$"

CURSEZONE_EventScript_YanFight_Text_41:
# 52 "data/maps/CURSEZONE/scripts.pory"
	.string "You've made it this far all by yourself.$"

CURSEZONE_EventScript_YanFight_Text_42:
# 53 "data/maps/CURSEZONE/scripts.pory"
	.string "Have you enjoyed it?$"

CURSEZONE_EventScript_YanFight_Text_43:
# 54 "data/maps/CURSEZONE/scripts.pory"
	.string "Peeling away all these memories...and dreams?$"

CURSEZONE_EventScript_YanFight_Text_44:
# 56 "data/maps/CURSEZONE/scripts.pory"
	.string "You don't even know, do you?$"

CURSEZONE_EventScript_YanFight_Text_45:
# 57 "data/maps/CURSEZONE/scripts.pory"
	.string "What you've been REALLY working towards?$"

CURSEZONE_EventScript_YanFight_Text_46:
# 58 "data/maps/CURSEZONE/scripts.pory"
	.string "She hasn't told you a thing.$"

CURSEZONE_EventScript_YanFight_Text_47:
# 59 "data/maps/CURSEZONE/scripts.pory"
	.string "You were never promised a reward.$"

CURSEZONE_EventScript_YanFight_Text_48:
# 60 "data/maps/CURSEZONE/scripts.pory"
	.string "It'll all be over soon anyway.$"

CURSEZONE_EventScript_YanFight_Text_49:
# 61 "data/maps/CURSEZONE/scripts.pory"
	.string "So in that case, I'll let you in\non a little secret,\n'{PLAYER}'$"

CURSEZONE_EventScript_YanFight_Text_50:
# 62 "data/maps/CURSEZONE/scripts.pory"
	.string "From the start, you've been on her\n path.$"

CURSEZONE_EventScript_YanFight_Text_51:
# 63 "data/maps/CURSEZONE/scripts.pory"
	.string "Maybe you've made some stops or\ndetours along the way, but...$"

CURSEZONE_EventScript_YanFight_Text_52:
# 64 "data/maps/CURSEZONE/scripts.pory"
	.string "The path you're on was always\ndesigned to end the same way.$"

CURSEZONE_EventScript_YanFight_Text_53:
# 65 "data/maps/CURSEZONE/scripts.pory"
	.string "....with me.$"

CURSEZONE_EventScript_YanFight_Text_54:
# 67 "data/maps/CURSEZONE/scripts.pory"
	.string "All that work...just for me. I'm\nflattered, really.$"

CURSEZONE_EventScript_YanFight_Text_55:
# 68 "data/maps/CURSEZONE/scripts.pory"
	.string "But...enough of this. You came\nhereto play a game.$"

CURSEZONE_EventScript_YanFight_Text_56:
# 69 "data/maps/CURSEZONE/scripts.pory"
	.string "Well, then, let's play.$"

CURSEZONE_EventScript_YanFight_Text_57:
# 70 "data/maps/CURSEZONE/scripts.pory"
	.string "I can see her in the back...smiling.\nShe's been waiting for this for\pa long time.$"

CURSEZONE_EventScript_YanFight_Text_58:
# 71 "data/maps/CURSEZONE/scripts.pory"
	.string "And I can't help but smile either.$"

YanIntro::
# 77 "data/maps/CURSEZONE/scripts.pory"
	.string "Well, here we go, {PLAYER}. Don't you know\nit's rude to keep ladies in waiting?$"

YanOutro::
# 81 "data/maps/CURSEZONE/scripts.pory"
	.string ".....$"
